name: ScriptBlock-Improved
version: $version
author: shirokuro
# Suppress warnings that reported if using 1.13+ servers
api-version: 1.13
description: Improved ScriptBlock
website: https://github.com/kuro46/ScriptBlock-Improved/
load: STARTUP
loadbefore:
  - Vault
main: xyz.shirokuro.scriptblockimproved.Bootstrap
commands:
  sbi:
    description: Main command of ScriptBlock-Improved
    usage: "Usage: /<command> help"
    permission: sbi.admin
permissions:
  sbi.*:
    default: op
    description: Main permission of ScriptBlock-Improved
    children:
      sbi.admin: true
  sbi.admin:
    default: op
    description: ScriptBlock-Improved administration permission.
